sudo: false
language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36,coveralls

install:
  - pip install tox

script:
  - tox

cache:
  - pip

deploy:
  provider: heroku
  on: master
  api_key:
    secure: "crCNmXJK7SqRGGsuKSwrukJTWsrvhegrXC3WcatsnW8a8JEJ3OhST8EJH5jesKyw7WdeoCcEhkcuPbL+nJv9v7FE0cz4xaY4zF/7K9lSnImMHIW0sKX4OvAGeFPmgw/ZQwOjtolA+FHi9pQtgIYnq8xEIQ7kmiCXA2G+ED+hejmqLmtWSK9tY/HvNwfoKRtYvZeM7ft1nmRQIrAZLrixdCCUVvkR2X0yMi1CRWpsVTMawTLTgUYT7N4U0DnPMijmQDFj27OGv0vaUNU8Htbh5Fy1HW0qKswalkv7qqSNC61vtVoRD4gxt4WwFjD+KjV740nrNVFc+yPDWS4XzHWN6qMT4/3K0pY4hBLCsBsBSQGmM82UeWLC6E6Tzvy6bGV8+UKAzPsIDN/fZSrhEmCek2WCDDg0P8ON9IJMHbTUd4tIGDqFVb+wsUaG0f4c6PZH1kCskG6N4Yqr6BbEsXDjquNK7SpY/6RWrq5QCgBR7vxqWf275paCwEt1zSHIPLSVnLJD7WT7Z4azXAx734QStwNZvyNemkV+gkXnQFaTNoyQW0/bfmm/lILjGLQDR+CrzLVBGGA+8Kt5d6rVQD+riP6J90ogzcx2YFAB0Ks9UyI8+H9JRWo4woeWLRQdWm5UqzTxjVe+XQiqFQt/A0cisvJMslpWXtcp0wCpS9lbBV0="
  app:
    secure: "f9WOqLo4EAAHFEuOTImatvfTibdf1lSy1QI88NprbDyp//5VVKlWCIu43tWVDgR80lEvrAlWwAesh4ijFz6AQe7QAmxsdnIJehILvN3NnT5Bafy0n8NtdieWzd1zMCnhX8LCUOsQY7E8eScTzYOiJsSeNz2rgosZC+AiNlVA3fBql0P2Z9/BKSTMZXjp3Y2wPwzkTsSd/bQm/ToJ2/ylLE2ZRjQBZk/cnDIoiLGqJjzIxaV/phQS/WWiLu6dh+z+pH/wQw1OU7XEAXHb4Jj9MMsXqMf7S+eT6LPR45R98cXrpmUzt0E0qu/0eCR0OVdPhCmjWohBWMPvsL1c6wQ9ZKC/n+9dnUpie1LlnJInBgl/iukaWSaOcGHhA5XRsDy9ErqgP1fJHCf8+FDRRR6oVbtKRqVRrleFgVUrl5VNN+QyxSoOUZseED248BO8FAkGLJPsN8KJLCM2L0yHp0z5mgow2WL8rS4s8DT3LlqJMjNTF+jvErHNFsyyrILMuQaFJoBINiDwa4V2UE+Q4cTxnj3h2Ldvk5LXBf73JeujauII1vYy3c/6hEoj7X1m2T1qGA9TOU9RY3uGC6O3j2qtdQwPdgWgy7cxwkNrSKQECfGhLS+o4qmTI5hZS7cDjCbCfTOsqKHyMs0XSp/TEciFm9teFe1+Xvp9j/IARjeneH4="
