sudo: false
language: python
matrix:
  include:
  - python: 3.6
    env: TOXENV=py36,coveralls
install:
- pip install tox
script:
- tox
cache:
- pip
after_success:
- echo $TRAVIS_COMMIT > version.txt
deploy:
  provider: heroku
  skip_cleanup: true
  on: master
  api_key:
    secure: H4xNpKUFa7UgH02mKNyQPSxe1VG44hggCqxzw02FQNfIh39unJ9YdOxt5CMmWh2C47e916dn9UpBjY1fC5B2EYuUekUQ+rN330IQ0wL4ZEOYjeL4cbHz9ktHvWwraRoVHIch5r9KG4Lbt9FLb8DPL0Ejt1Zx/NUjAoXrp8GfY+VfT7J0Qa5z8FRaNuks5uEI4y/JCX6bNSH10Y8M748971R6NxtAn2G7/TJA5Yhu9bIPPdiWSa6feBMAoR4MGG1BKFigbaU3Hh95+J5kGhMMCXk36cyx4D9z22rpLcpHit2kFm/7mgDvNL47srFLoOBoNSe8mPY+GakljskeuPn46413gSQy5yfsmoS7CoXmQ2TP7T5al88F+Fypp69+bDPFAk0DKJSChYjUC8so7p5Rz4eM/B6g18hxbXbkDW3EBrwIJcTHorO+Qs2vdHhV5MWl3asScFW5iS2NqLMf9z9IEte85v70u+65tYq7qEIs31UPZpd+6k5Hz4ziLoAN+xStl/jjyaar9mBbYxruz+H7AzIesCrhR/2qxDy47bCmslPUhPSkmSQ1BZGFoZIcAahQ1vbn5VjrPIq9PvBL7wTaLRz9DJflQF1eOHDPD9fKzyYOnkM4VsC2Qdmy72MoiwEj1jV2TFtgjB3sJEfpwRucZugb+2Bc2+9JcnckAj8NV7w=
  app:
    secure: RdHFs5jOZOEW1DEd7tcH8q82vpzTCVnV2suQlsKFnf5aeduAKW8yuKuTtq1ySUItE40FOCWjnGqqYfmAkvEgjb08Tt1bVfT8ix0l72XFV/pHT81gPDj1VpsKEE0LoMZbdhW7XlTZD6GI8YEHkQGix146iXRS3AuXU338VujB4WEzSF/8hh+KuuVLvP3ZbhxPAZxe1CKDhn9CyjYbwKnNN6eq3RNh6pjGX7VmAyZ7yO/cP6rMOEuC80CV8aeqbH0rSpAuvTjh0INWu3yCw7kSJOfRyUgzUhbVFYQ9DWYF4ApA5QsletN9iQfwIZE1UNbthtyXtaEfW/1RM2KOLpV7w+sateaxj0SUljNdpym9HExMJSsY08mmQl55nQFAXPVjDz7evHimXd+iI2Q7KAdeceArOEOMAIxZqZ4nRrRzBWGT5tQEdHmRxFjpPMdyliorU6LromtQLYsYXr5xy0+sdiR8gtkr5YQcVhtMnXrApBQ8Z2e583EtAVZrq5ok1JSpUIySPGrBDNDXTGaBU7uT7yUUDLlRWZC6s6X4qtl25pqOCWfm0mHZpoXGL8byOmJG6LqlEMdWG61aL3XhRljnbPJjiFKwrFV/txu/2dQwYP3hOh3jOF90aZLYHfqdfSrsnRP7Xaw4BgTtev1F6+TZe+zvryfjDqT2q2ciELZVS8I=
