version: '3'

services:

  #client:
  #  image: irssi
  #  entrypoint: ["cat"]
  #  stdin_open: true
  #  tty: true

  ircbot:
    build:
      context: .
    environment:
      SERVER_NAME: "ircserver"
      SERVER_PORT: "6667"
      CHANNEL_NAME: "#testchannel"
      NICK: "stockmurph"
      LOGLEVEL: "DEBUG"
      DATABASE_URL: "postgres://bot:password@database:5432/ircbotdb"
      SCHEDULER: "true"
      LYHEDEN_BASE_URL: ${LYHEDEN_BASE_URL}
      LYHEDEN_USERNAME: ${LYHEDEN_USERNAME}
      LYHEDEN_PASSWORD: ${LYHEDEN_PASSWORD}

  ircserver:
    image: inspircd/inspircd-docker:latest
    ports:
    - "6667:6667"

  database:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: "ircbotdb"
      POSTGRES_USER: "bot"
      POSTGRES_PASSWORD: "password"
